// ram_2p.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module ram_2p (
		input  wire [31:0] data,      //  ram_input.datain
		input  wire [8:0]  wraddress, //           .wraddress
		input  wire [8:0]  rdaddress, //           .rdaddress
		input  wire        wren,      //           .wren
		input  wire        clock,     //           .clock
		output wire [31:0] q          // ram_output.dataout
	);

	ram_2p_ram_2port_180_phloncy ram_2p (
		.data      (data),      //   input,  width = 32,  ram_input.datain
		.wraddress (wraddress), //   input,   width = 9,           .wraddress
		.rdaddress (rdaddress), //   input,   width = 9,           .rdaddress
		.wren      (wren),      //   input,   width = 1,           .wren
		.clock     (clock),     //   input,   width = 1,           .clock
		.q         (q)          //  output,  width = 32, ram_output.dataout
	);

endmodule
