// eth_mdio.v

// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module eth_mdio (
		input  wire        clk,             //       clock.clk
		input  wire        reset,           // clock_reset.reset
		input  wire        csr_write,       //         csr.write
		input  wire        csr_read,        //            .read
		input  wire [5:0]  csr_address,     //            .address
		input  wire [31:0] csr_writedata,   //            .writedata
		output wire [31:0] csr_readdata,    //            .readdata
		output wire        csr_waitrequest, //            .waitrequest
		output wire        mdc,             //        mdio.mdc
		input  wire        mdio_in,         //            .mdio_in
		output wire        mdio_out,        //            .mdio_out
		output wire        mdio_oen         //            .mdio_oen
	);

	altera_eth_mdio #(
		.MDC_DIVISOR (50)
	) eth_mdio_0 (
		.clk             (clk),             //       clock.clk
		.reset           (reset),           // clock_reset.reset
		.csr_write       (csr_write),       //         csr.write
		.csr_read        (csr_read),        //            .read
		.csr_address     (csr_address),     //            .address
		.csr_writedata   (csr_writedata),   //            .writedata
		.csr_readdata    (csr_readdata),    //            .readdata
		.csr_waitrequest (csr_waitrequest), //            .waitrequest
		.mdc             (mdc),             //        mdio.export
		.mdio_in         (mdio_in),         //            .export
		.mdio_out        (mdio_out),        //            .export
		.mdio_oen        (mdio_oen)         //            .export
	);

endmodule
