// tse_altera_eth_tse_180_4odqu6q.v

// This file was auto-generated from altera_eth_tse_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module tse_altera_eth_tse_180_4odqu6q (
		input  wire [4:0]  reg_addr,       //                  control_port.address
		output wire [15:0] reg_data_out,   //                              .readdata
		input  wire        reg_rd,         //                              .read
		input  wire [15:0] reg_data_in,    //                              .writedata
		input  wire        reg_wr,         //                              .write
		output wire        reg_busy,       //                              .waitrequest
		input  wire        clk,            // control_port_clock_connection.clk
		output wire        gmii_rx_dv,     //               gmii_connection.gmii_rx_dv
		output wire [7:0]  gmii_rx_d,      //                              .gmii_rx_d
		output wire        gmii_rx_err,    //                              .gmii_rx_err
		input  wire        gmii_tx_en,     //                              .gmii_tx_en
		input  wire [7:0]  gmii_tx_d,      //                              .gmii_tx_d
		input  wire        gmii_tx_err,    //                              .gmii_tx_err
		output wire        rx_clk,         //  pcs_receive_clock_connection.clk
		input  wire        reset_rx_clk,   //  pcs_receive_reset_connection.reset
		input  wire        ref_clk,        //  pcs_ref_clk_clock_connection.clk
		output wire        tx_clk,         // pcs_transmit_clock_connection.clk
		input  wire        reset_tx_clk,   // pcs_transmit_reset_connection.reset
		input  wire        reset,          //              reset_connection.reset
		output wire        rx_recovclkout, //     serdes_control_connection.export
		input  wire        rxp,            //             serial_connection.rxp_0
		output wire        txp,            //                              .txp_0
		output wire        led_crs,        //         status_led_connection.crs
		output wire        led_link,       //                              .link
		output wire        led_panel_link, //                              .panel_link
		output wire        led_col,        //                              .col
		output wire        led_an,         //                              .an
		output wire        led_char_err,   //                              .char_err
		output wire        led_disp_err    //                              .disp_err
	);

	wire        i_lvdsio_terminator_0_lvds_rx_inclock_export;                          // i_lvdsio_terminator_0:lvds_rx_inclock -> i_lvdsio_rx_0:inclock
	wire  [9:0] i_lvdsio_rx_0_rx_out_export;                                           // i_lvdsio_rx_0:rx_out -> i_lvdsio_terminator_0:rx_out
	wire  [0:0] i_lvdsio_terminator_0_rx_in_export;                                    // i_lvdsio_terminator_0:rx_in -> i_lvdsio_rx_0:rx_in
	wire  [0:0] i_lvdsio_terminator_0_rx_dpa_reset_export;                             // i_lvdsio_terminator_0:rx_dpa_reset -> i_lvdsio_rx_0:rx_dpa_reset
	wire  [0:0] i_lvdsio_rx_0_rx_dpa_locked_export;                                    // i_lvdsio_rx_0:rx_dpa_locked -> i_lvdsio_terminator_0:rx_dpa_locked
	wire  [0:0] i_lvdsio_rx_0_rx_divfwdclk_export;                                     // i_lvdsio_rx_0:rx_divfwdclk -> i_lvdsio_terminator_0:rx_divfwdclk
	wire        i_lvdsio_rx_0_rx_coreclock_export;                                     // i_lvdsio_rx_0:rx_coreclock -> i_lvdsio_terminator_0:rx_coreclock
	wire        i_lvdsio_rx_0_pll_locked_export;                                       // i_lvdsio_rx_0:pll_locked -> i_lvdsio_terminator_0:pll_locked_rx
	wire        i_lvdsio_terminator_0_pll_areset_rx_export;                            // i_lvdsio_terminator_0:pll_areset_rx -> i_lvdsio_rx_0:pll_areset
	wire        i_lvdsio_terminator_0_lvds_tx_inclock_export;                          // i_lvdsio_terminator_0:lvds_tx_inclock -> i_lvdsio_tx_0:inclock
	wire  [9:0] i_lvdsio_terminator_0_tx_in_export;                                    // i_lvdsio_terminator_0:tx_in -> i_lvdsio_tx_0:tx_in
	wire  [0:0] i_lvdsio_tx_0_tx_out_export;                                           // i_lvdsio_tx_0:tx_out -> i_lvdsio_terminator_0:tx_out
	wire        i_lvdsio_tx_0_pll_locked_export;                                       // i_lvdsio_tx_0:pll_locked -> i_lvdsio_terminator_0:pll_locked_tx
	wire        i_lvdsio_terminator_0_pll_areset_tx_export;                            // i_lvdsio_terminator_0:pll_areset_tx -> i_lvdsio_tx_0:pll_areset
	wire  [9:0] i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed;                             // i_tse_pcs_0:tbi_tx_d_muxed -> i_lvdsio_terminator_0:tbi_tx_d_muxed_0
	wire  [9:0] i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds;                   // i_lvdsio_terminator_0:tbi_rx_d_lvds_0 -> i_tse_pcs_0:tbi_rx_d_lvds
	wire        i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk;                         // i_lvdsio_terminator_0:tbi_rx_clk_0 -> i_tse_pcs_0:tbi_rx_clk
	wire        i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done; // i_lvdsio_terminator_0:rx_reset_sequence_done_0 -> i_tse_pcs_0:rx_reset_sequence_done
	wire        i_lvdsio_terminator_0_rx_reset_0_rx_reset;                             // i_lvdsio_terminator_0:rx_reset_0 -> i_tse_pcs_0:rx_reset
	wire        i_lvdsio_terminator_0_tx_reset_0_tx_reset;                             // i_lvdsio_terminator_0:tx_reset_0 -> i_tse_pcs_0:tx_reset

	altera_eth_tse_pcs_pma_nf_lvds #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (4608),
		.ENABLE_ECC          (0),
		.ENABLE_REV_LOOPBACK (0),
		.DEVICE_FAMILY       ("ARRIA10"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (0),
		.ENABLE_SGMII        (0),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_0 (
		.clk                    (clk),                                                                   //   input,   width = 1, control_port_clock_connection.clk
		.reset                  (reset),                                                                 //   input,   width = 1,              reset_connection.reset
		.reg_addr               (reg_addr),                                                              //   input,   width = 5,                  control_port.address
		.reg_data_out           (reg_data_out),                                                          //  output,  width = 16,                              .readdata
		.reg_rd                 (reg_rd),                                                                //   input,   width = 1,                              .read
		.reg_data_in            (reg_data_in),                                                           //   input,  width = 16,                              .writedata
		.reg_wr                 (reg_wr),                                                                //   input,   width = 1,                              .write
		.reg_busy               (reg_busy),                                                              //  output,   width = 1,                              .waitrequest
		.ref_clk                (ref_clk),                                                               //   input,   width = 1,  pcs_ref_clk_clock_connection.clk
		.gmii_rx_dv             (gmii_rx_dv),                                                            //  output,   width = 1,               gmii_connection.gmii_rx_dv
		.gmii_rx_d              (gmii_rx_d),                                                             //  output,   width = 8,                              .gmii_rx_d
		.gmii_rx_err            (gmii_rx_err),                                                           //  output,   width = 1,                              .gmii_rx_err
		.gmii_tx_en             (gmii_tx_en),                                                            //   input,   width = 1,                              .gmii_tx_en
		.gmii_tx_d              (gmii_tx_d),                                                             //   input,   width = 8,                              .gmii_tx_d
		.gmii_tx_err            (gmii_tx_err),                                                           //   input,   width = 1,                              .gmii_tx_err
		.tx_clk                 (tx_clk),                                                                //  output,   width = 1, pcs_transmit_clock_connection.clk
		.rx_clk                 (rx_clk),                                                                //  output,   width = 1,  pcs_receive_clock_connection.clk
		.reset_tx_clk           (reset_tx_clk),                                                          //   input,   width = 1, pcs_transmit_reset_connection.reset
		.reset_rx_clk           (reset_rx_clk),                                                          //   input,   width = 1,  pcs_receive_reset_connection.reset
		.led_crs                (led_crs),                                                               //  output,   width = 1,         status_led_connection.export
		.led_link               (led_link),                                                              //  output,   width = 1,                              .export
		.led_panel_link         (led_panel_link),                                                        //  output,   width = 1,                              .export
		.led_col                (led_col),                                                               //  output,   width = 1,                              .export
		.led_an                 (led_an),                                                                //  output,   width = 1,                              .export
		.led_char_err           (led_char_err),                                                          //  output,   width = 1,                              .export
		.led_disp_err           (led_disp_err),                                                          //  output,   width = 1,                              .export
		.rx_recovclkout         (rx_recovclkout),                                                        //  output,   width = 1,     serdes_control_connection.export
		.rx_reset               (i_lvdsio_terminator_0_rx_reset_0_rx_reset),                             //   input,   width = 1,                      rx_reset.rx_reset
		.rx_reset_sequence_done (i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done), //   input,   width = 1,        rx_reset_sequence_done.rx_reset_sequence_done
		.tbi_rx_clk             (i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk),                         //   input,   width = 1,                    tbi_rx_clk.tbi_rx_clk
		.tx_reset               (i_lvdsio_terminator_0_tx_reset_0_tx_reset),                             //   input,   width = 1,                      tx_reset.tx_reset
		.tbi_tx_d_muxed         (i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //  output,  width = 10,                tbi_tx_d_muxed.tbi_tx_d_muxed
		.tbi_rx_d_lvds          (i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds),                   //   input,  width = 10,                 tbi_rx_d_lvds.tbi_rx_d_lvds
		.tx_clkena              (),                                                                      // (terminated),                                            
		.rx_clkena              (),                                                                      // (terminated),                                            
		.mii_rx_dv              (),                                                                      // (terminated),                                            
		.mii_rx_d               (),                                                                      // (terminated),                                            
		.mii_rx_err             (),                                                                      // (terminated),                                            
		.mii_tx_en              (1'b0),                                                                  // (terminated),                                            
		.mii_tx_d               (4'b0000),                                                               // (terminated),                                            
		.mii_tx_err             (1'b0),                                                                  // (terminated),                                            
		.mii_col                (),                                                                      // (terminated),                                            
		.mii_crs                (),                                                                      // (terminated),                                            
		.set_10                 (),                                                                      // (terminated),                                            
		.set_1000               (),                                                                      // (terminated),                                            
		.set_100                (),                                                                      // (terminated),                                            
		.hd_ena                 (),                                                                      // (terminated),                                            
		.pcs_phase_measure_clk  (1'b0),                                                                  // (terminated),                                            
		.rx_latency_adj         (),                                                                      // (terminated),                                            
		.tx_latency_adj         (),                                                                      // (terminated),                                            
		.tx_ptp_alignment       (),                                                                      // (terminated),                                            
		.pcs_eccstatus          ()                                                                       // (terminated),                                            
	);

	altera_eth_tse_nf_lvds_terminator #(
		.NUM_CHANNELS       (1),
		.SYNCHRONIZER_DEPTH (3),
		.DEVICE_FAMILY      ("ARRIA10")
	) i_lvdsio_terminator_0 (
		.lvds_inclock              (ref_clk),                                                               //   input,   width = 1,             lvds_inclock.clk
		.reset                     (reset),                                                                 //   input,   width = 1,                 reset_in.reset
		.lvds_rx_inclock           (i_lvdsio_terminator_0_lvds_rx_inclock_export),                          //  output,   width = 1,          lvds_rx_inclock.export
		.pll_areset_duplex         (),                                                                      //  output,   width = 1,        pll_areset_duplex.export
		.pll_areset_rx             (i_lvdsio_terminator_0_pll_areset_rx_export),                            //  output,   width = 1,            pll_areset_rx.export
		.pll_locked_tx             (i_lvdsio_tx_0_pll_locked_export),                                       //   input,   width = 1,            pll_locked_tx.export
		.lvds_tx_inclock           (i_lvdsio_terminator_0_lvds_tx_inclock_export),                          //  output,   width = 1,          lvds_tx_inclock.export
		.rx_coreclock              (i_lvdsio_rx_0_rx_coreclock_export),                                     //   input,   width = 1,             rx_coreclock.export
		.pll_areset_tx             (i_lvdsio_terminator_0_pll_areset_tx_export),                            //  output,   width = 1,            pll_areset_tx.export
		.pll_locked_rx             (i_lvdsio_rx_0_pll_locked_export),                                       //   input,   width = 1,            pll_locked_rx.export
		.rx_dpa_reset              (i_lvdsio_terminator_0_rx_dpa_reset_export),                             //  output,   width = 1,             rx_dpa_reset.export
		.rx_in                     (i_lvdsio_terminator_0_rx_in_export),                                    //  output,   width = 1,                    rx_in.export
		.rx_out                    (i_lvdsio_rx_0_rx_out_export),                                           //   input,  width = 10,                   rx_out.export
		.tx_in                     (i_lvdsio_terminator_0_tx_in_export),                                    //  output,  width = 10,                    tx_in.export
		.rx_dpa_locked             (i_lvdsio_rx_0_rx_dpa_locked_export),                                    //   input,   width = 1,            rx_dpa_locked.export
		.rx_divfwdclk              (i_lvdsio_rx_0_rx_divfwdclk_export),                                     //   input,   width = 1,             rx_divfwdclk.export
		.tx_out                    (i_lvdsio_tx_0_tx_out_export),                                           //   input,   width = 1,                   tx_out.export
		.rxp_0                     (rxp),                                                                   //   input,   width = 1,      serial_connection_0.export
		.txp_0                     (txp),                                                                   //  output,   width = 1,                         .export
		.rx_reset_0                (i_lvdsio_terminator_0_rx_reset_0_rx_reset),                             //  output,   width = 1,               rx_reset_0.rx_reset
		.rx_reset_sequence_done_0  (i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done), //  output,   width = 1, rx_reset_sequence_done_0.rx_reset_sequence_done
		.tbi_rx_clk_0              (i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk),                         //  output,   width = 1,             tbi_rx_clk_0.tbi_rx_clk
		.tx_reset_0                (i_lvdsio_terminator_0_tx_reset_0_tx_reset),                             //  output,   width = 1,               tx_reset_0.tx_reset
		.tbi_rx_d_lvds_0           (i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds),                   //  output,  width = 10,          tbi_rx_d_lvds_0.tbi_rx_d_lvds
		.tbi_tx_d_muxed_0          (i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //   input,  width = 10,         tbi_tx_d_muxed_0.tbi_tx_d_muxed
		.pll_locked_duplex         (1'b0),                                                                  // (terminated),                                       
		.rxp_1                     (1'b0),                                                                  // (terminated),                                       
		.txp_1                     (),                                                                      // (terminated),                                       
		.rx_reset_1                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_1  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_1              (),                                                                      // (terminated),                                       
		.tx_reset_1                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_1           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_1          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_2                     (1'b0),                                                                  // (terminated),                                       
		.txp_2                     (),                                                                      // (terminated),                                       
		.rx_reset_2                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_2  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_2              (),                                                                      // (terminated),                                       
		.tx_reset_2                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_2           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_2          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_3                     (1'b0),                                                                  // (terminated),                                       
		.txp_3                     (),                                                                      // (terminated),                                       
		.rx_reset_3                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_3  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_3              (),                                                                      // (terminated),                                       
		.tx_reset_3                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_3           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_3          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_4                     (1'b0),                                                                  // (terminated),                                       
		.txp_4                     (),                                                                      // (terminated),                                       
		.rx_reset_4                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_4  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_4              (),                                                                      // (terminated),                                       
		.tx_reset_4                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_4           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_4          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_5                     (1'b0),                                                                  // (terminated),                                       
		.txp_5                     (),                                                                      // (terminated),                                       
		.rx_reset_5                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_5  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_5              (),                                                                      // (terminated),                                       
		.tx_reset_5                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_5           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_5          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_6                     (1'b0),                                                                  // (terminated),                                       
		.txp_6                     (),                                                                      // (terminated),                                       
		.rx_reset_6                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_6  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_6              (),                                                                      // (terminated),                                       
		.tx_reset_6                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_6           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_6          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_7                     (1'b0),                                                                  // (terminated),                                       
		.txp_7                     (),                                                                      // (terminated),                                       
		.rx_reset_7                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_7  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_7              (),                                                                      // (terminated),                                       
		.tx_reset_7                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_7           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_7          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_8                     (1'b0),                                                                  // (terminated),                                       
		.txp_8                     (),                                                                      // (terminated),                                       
		.rx_reset_8                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_8  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_8              (),                                                                      // (terminated),                                       
		.tx_reset_8                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_8           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_8          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_9                     (1'b0),                                                                  // (terminated),                                       
		.txp_9                     (),                                                                      // (terminated),                                       
		.rx_reset_9                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_9  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_9              (),                                                                      // (terminated),                                       
		.tx_reset_9                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_9           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_9          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_10                    (1'b0),                                                                  // (terminated),                                       
		.txp_10                    (),                                                                      // (terminated),                                       
		.rx_reset_10               (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_10 (),                                                                      // (terminated),                                       
		.tbi_rx_clk_10             (),                                                                      // (terminated),                                       
		.tx_reset_10               (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_10          (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_10         (10'b0000000000),                                                        // (terminated),                                       
		.rxp_11                    (1'b0),                                                                  // (terminated),                                       
		.txp_11                    (),                                                                      // (terminated),                                       
		.rx_reset_11               (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_11 (),                                                                      // (terminated),                                       
		.tbi_rx_clk_11             (),                                                                      // (terminated),                                       
		.tx_reset_11               (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_11          (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_11         (10'b0000000000)                                                         // (terminated),                                       
	);

	tse_altera_lvds_180_rc52bha i_lvdsio_rx_0 (
		.inclock       (i_lvdsio_terminator_0_lvds_rx_inclock_export), //   input,   width = 1,       inclock.export
		.pll_areset    (i_lvdsio_terminator_0_pll_areset_rx_export),   //   input,   width = 1,    pll_areset.export
		.pll_locked    (i_lvdsio_rx_0_pll_locked_export),              //  output,   width = 1,    pll_locked.export
		.rx_coreclock  (i_lvdsio_rx_0_rx_coreclock_export),            //  output,   width = 1,  rx_coreclock.export
		.rx_divfwdclk  (i_lvdsio_rx_0_rx_divfwdclk_export),            //  output,   width = 1,  rx_divfwdclk.export
		.rx_dpa_locked (i_lvdsio_rx_0_rx_dpa_locked_export),           //  output,   width = 1, rx_dpa_locked.export
		.rx_dpa_reset  (i_lvdsio_terminator_0_rx_dpa_reset_export),    //   input,   width = 1,  rx_dpa_reset.export
		.rx_in         (i_lvdsio_terminator_0_rx_in_export),           //   input,   width = 1,         rx_in.export
		.rx_out        (i_lvdsio_rx_0_rx_out_export)                   //  output,  width = 10,        rx_out.export
	);

	tse_altera_lvds_180_phldzry i_lvdsio_tx_0 (
		.inclock    (i_lvdsio_terminator_0_lvds_tx_inclock_export), //   input,   width = 1,    inclock.export
		.pll_areset (i_lvdsio_terminator_0_pll_areset_tx_export),   //   input,   width = 1, pll_areset.export
		.pll_locked (i_lvdsio_tx_0_pll_locked_export),              //  output,   width = 1, pll_locked.export
		.tx_in      (i_lvdsio_terminator_0_tx_in_export),           //   input,  width = 10,      tx_in.export
		.tx_out     (i_lvdsio_tx_0_tx_out_export)                   //  output,   width = 1,     tx_out.export
	);

endmodule
